import { createSlice } from "@reduxjs/toolkit"

const initialState = {
    value: [
        {
            id: 1,
            title: 'A',
            items: [
              'Armani',
              'Acqua Di Parma',
              'Aerin Lauder',
              'Afnan',
              'Agent Provocateur',
              'Agonist',
              'Ajmal',
              'Al Haramain',
              'Al Rehab',
              'Amouage',
            ],
          },
          {
            id: 2,
            title: 'B',
            items: [
              'Baldessarini',
              'Balenciaga',
              'Banana Republic',
              'Bath & Body Works',
              'BDK Parfums',
              'Bentley',
              'Blend Oud',
              'Bond No.9',
              'Boucheron',
              'Burberry',
            ],
          },
          {
            id: 3,
            title: 'C',
            items: [
              'Calvin Klein',
              'Carolina Herrera',
              'Cartier',
              'Cerruti',
              'Chanel',
              'Chloe',
              'Christian Dior',
              'Clive Christian',
              'Creed',
              'Comme des Garçons',
            ],
          },
          {
            id: 4,
            title: 'D',
            items: [
              'Dior',
              'Dolce & Gabbana',
              'Davidoff',
              'Diptyque',
              'Diesel',
              'Donna Karan',
              'Dsquared2',
              'Dunhill',
              'Drakkar Noir',
              'Demeter',
            ],
          },
          {
            id: 5,
            title: 'E',
            items: [
              'Elizabeth Arden',
              'Escada',
              'Elie Saab',
              'Ermenegildo Zegna',
              'Etro',
              'Escentric Molecules',
              'Estee Lauder',
              'Etat Libre d’Orange',
              'Erba Pura',
              'Eisenberg',
            ],
          },
          {
            id: 6,
            title: 'F',
            items: [
              'Ferrari',
              'Fendi',
              'Frederic Malle',
              'Floris',
              'Franck Boclet',
              'French Lover',
              'Fugazzi',
              'Faberge',
              'Fenty',
              'Farmacia SS. Annunziata',
            ],
          },
          {
            id: 7,
            title: 'G',
            items: [
              'Gucci',
              'Guerlain',
              'Giorgio Beverly Hills',
              'Gres',
              'Giorgio Armani',
              'Givenchy',
              'Geoffrey Beene',
              'Goldfield & Banks',
              'Goutal',
              'Granado',
            ],
          },
          {
            id: 8,
            title: 'H',
            items: [
              'Hermès',
              'Hugo Boss',
              'Helmut Lang',
              'Histoires de Parfums',
              'Halston',
              'House of Sillage',
              'Harajuku Lovers',
              'Henry Jacques',
              'Honoré des Prés',
              'Hanae Mori',
            ],
          },
          {
            id: 9,
            title: 'I',
            items: [
              'Issey Miyake',
              'Imaginary Authors',
              'Initio Parfums',
              'Il Profvmo',
              'Indult',
              'Ineke',
              'Iris Prima',
              'Isabey',
              'Iceberg',
              'Idole d’Armani',
            ],
          },
          {
            id: 10,
            title: 'J',
            items: [
              'Jo Malone',
              'Jean Paul Gaultier',
              'Jimmy Choo',
              'Jacques Fath',
              'Jaguar',
              'Jennifer Lopez',
              'Jil Sander',
              'John Varvatos',
              'Juicy Couture',
              'Juliette Has a Gun',
            ],
          },
          {
            id: 11,
            title: 'K',
            items: [
              'Kenzo',
              'Kilian',
              'Karl Lagerfeld',
              'Kelsey Berwin',
              'Keiko Mecheri',
              'Krizia',
              'Kouros',
              'Kate Spade',
              'KORRES',
              'Krigler',
            ],
          },
          {
            id: 12,
            title: 'L',
            items: [
              'Lancôme',
              'Lalique',
              'Loewe',
              'Lush',
              'Lolita Lempicka',
              'L’Artisan Parfumeur',
              'La Prairie',
              'Le Labo',
              'Lorenzo Villoresi',
              'Louis Vuitton',
            ],
          },
          {
            id: 13,
            title: 'M',
            items: [
              'Montblanc',
              'Mugler',
              'Maison Francis Kurkdjian',
              'Marc Jacobs',
              'Michael Kors',
              'Masque Milano',
              'Mancera',
              'Memo Paris',
              'Mizensir',
              'Missoni',
            ],
          },
          {
            id: 14,
            title: 'N',
            items: [
              'Narciso Rodriguez',
              'Nina Ricci',
              'Nobile 1942',
              'Nasomatto',
              'New York Oud',
              'Nishane',
              'Nike',
              'Nicki Minaj',
              'Nars',
              'Nautica',
            ],
          },
          {
            id: 15,
            title: 'O',
            items: [
              'Oscar de la Renta',
              'Ormonde Jayne',
              'Olivier Durbano',
              'Oud Stars',
              'Oriflame',
              'Orto Parisi',
              'Odyssey',
              'Off-White',
              'Old Spice',
              'Oakcha',
            ],
          },
          {
            id: 16,
            title: 'P',
            items: [
              'Prada',
              'Paco Rabanne',
              'Penhaligon’s',
              'Parfums de Marly',
              'Philosophy',
              'Police',
              'Pierre Balmain',
              'Paul Smith',
              'Perry Ellis',
              'Pierre Cardin',
            ],
          },
          {
            id: 17,
            title: 'Q',
            items: [
              'Qasamat',
              'Qatar Perfume',
              'Queen Latifah',
              'Quintessence',
              'Quorum',
              'Quinta Essenza',
              'Quasar',
              'Quantum Oud',
              'Quetzel',
              'Queen’s Secret',
            ],
          },
          {
            id: 18,
            title: 'R',
            items: [
              'Ralph Lauren',
              'Rasasi',
              'Roberto Cavalli',
              'Rochas',
              'Roger & Gallet',
              'Roja Parfums',
              'Royal Crown',
              'Rihanah',
              'Reminiscence',
              'Revlon',
            ],
          },
          {
            id: 19,
            title: 'S',
            items: [
              'Salvatore Ferragamo',
              'Shiseido',
              'Sisley',
              'Serge Lutens',
              'Swiss Arabian',
              'Scandal',
              'S.T. Dupont',
              'Sarah Jessica Parker',
              'Sean John',
              'Swarovski',
            ],
          },
          {
            id: 20,
            title: 'T',
            items: [
              'Tom Ford',
              'Trussardi',
              'Ted Baker',
              'Thierry Mugler',
              'Tiffany & Co.',
              'Tiziana Terenzi',
              'The Body Shop',
              'Taylor Swift',
              'The Harmonist',
              'Tocca',
            ],
          },
          {
            id: 21,
            title: 'U',
            items: [
              'Ungaro',
              'Usher',
              'Utopia',
              'UOMO',
              'Ulric de Varens',
              'Uncut Gem',
              'Urban Scents',
              'Union Fragrance',
              'Ulfactory',
              'Ulta Fragrance',
            ],
          },
          {
            id: 22,
            title: 'V',
            items: [
              'Versace',
              'Valentino',
              'Van Cleef & Arpels',
              'Victoria’s Secret',
              'Vera Wang',
              'Vilhelm Parfumerie',
              'Vilhelm Fragrance',
              'Voyage',
              'Vanitas',
              'Vetiver',
            ],
          },
          {
            id: 23,
            title: 'W',
            items: [
              'Woody',
              'William Owen',
              'Wildfox',
              'Wilger',
              'White Linen',
              'Widian',
              'Wind Song',
              'Warm Cotton',
              'Wisteria',
              'Wickes',
            ],
          },
          {
            id: 24,
            title: 'X',
            items: [
              'Xerjoff',
              'XOXO',
              'Xoudou',
              'Xyrena',
              'Xchange Fragrance',
              'X1 Fragrance',
              'Xolotl',
              'X-perfumes',
              'XEDRA',
              'Xclusive',
            ],
          },
          {
            id: 25,
            title: 'Y',
            items: [
              'Yves Saint Laurent',
              'Yankee Candle',
              'Yardley London',
              'Yzy Perfumes',
              'YSL Libre',
              'Yves Rocher',
              'Ylang Ylang',
              'Yes I Am',
              'Younique',
              'Yardly Delight',
            ],
          },
          {
            id: 26,
            title: 'Z',
            items: [
              'Zara',
              'Zegna',
              'Zirh',
              'Zoella',
              'Zents',
              'Zarkoperfume',
              'Zero Plus',
              'Zoologist',
              'Zen by Shiseido',
              'Zegna Forte',
            ],
          },
    ],
    activeItem: null
}

export const MenuSlice = createSlice({
    name: 'menuItem',
    initialState,
    reducers: {
        setActiveItem: (state, action) => {
            state.activeItem = action.payload;
        },
    },
})

export const { setActiveItem } = MenuSlice.actions

export default MenuSlice.reducer